//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Script/Input System/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""Diplocaulus"",
            ""id"": ""41c58bd0-582f-4037-a50b-ae02690cc054"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""79865c3a-241e-4a27-8860-b3e39c514703"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Collect"",
                    ""type"": ""Button"",
                    ""id"": ""996653c3-6604-4efc-8391-82563ac7d45c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BabyFollow"",
                    ""type"": ""Button"",
                    ""id"": ""9dffdc90-7497-4137-9971-85d40ad148f6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BabyAction"",
                    ""type"": ""Button"",
                    ""id"": ""d991b565-7440-4f94-ae92-031e173a67c6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CamMove"",
                    ""type"": ""PassThrough"",
                    ""id"": ""e2f66674-8ae3-49f7-9cac-60a578dd91b9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CamReset"",
                    ""type"": ""Button"",
                    ""id"": ""e1f73a60-d732-4b6c-9949-c051c2ad2ea6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Letters"",
                    ""id"": ""35a06ad6-abbe-44b7-9195-854abcf5fed4"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""3f24064e-1b48-4537-8e86-79def926e16f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""71a46659-82d3-4e14-a36f-d205ea75eae6"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""d574440f-4a0f-4d4a-aa91-4d0932dd3206"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""d4bb1340-3263-40a1-9002-386fe501725b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""bdeaa727-3bf8-415b-8d26-087773f80999"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""db57630f-b384-48e1-a629-7a4b1709ab4f"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b1bd3ff9-eb4e-4859-9793-762fba0c26e5"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""c5951e13-555b-4e13-ab7d-8c2eb70899e4"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""1c2d2437-b9e7-4667-bb8c-e80cddb0df90"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""da2cc704-261c-4465-ba8c-fdbec048cbf9"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Collect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e48e758a-6a1f-4a0a-846a-432eae36d7bf"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Collect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""576d7317-89f6-4106-b176-963f05a84c41"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BabyFollow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d37802e1-7731-442c-971e-3c7fca2eff50"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BabyFollow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""19b03893-6319-4a33-a9c6-a87c3684cab7"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BabyAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""01e2fc1f-4a09-4923-831e-22f9f4c0ca7d"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BabyAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""a06d36c8-83e7-4a7d-a80e-dcdbf1181a73"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CamMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b0be2f31-5fea-4589-8ae8-f6c23aacdc3c"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CamMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f5ce4cc9-b346-49cb-85d0-cd229aeef3d9"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CamMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""fbd3a4f0-21ad-4882-9e10-875921b22ad4"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CamMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""28c4a691-d385-4fc0-af7a-ad1f9b1ca16c"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CamMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""7ce2599e-95a7-4a78-bbe8-b002f12210de"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CamMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""54171a33-8ce2-48ea-b75f-23c67a83adee"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CamReset"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""955fc922-63a7-4143-bd0c-aa18cbb79817"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CamReset"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Diplocaulus
        m_Diplocaulus = asset.FindActionMap("Diplocaulus", throwIfNotFound: true);
        m_Diplocaulus_Move = m_Diplocaulus.FindAction("Move", throwIfNotFound: true);
        m_Diplocaulus_Collect = m_Diplocaulus.FindAction("Collect", throwIfNotFound: true);
        m_Diplocaulus_BabyFollow = m_Diplocaulus.FindAction("BabyFollow", throwIfNotFound: true);
        m_Diplocaulus_BabyAction = m_Diplocaulus.FindAction("BabyAction", throwIfNotFound: true);
        m_Diplocaulus_CamMove = m_Diplocaulus.FindAction("CamMove", throwIfNotFound: true);
        m_Diplocaulus_CamReset = m_Diplocaulus.FindAction("CamReset", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Diplocaulus
    private readonly InputActionMap m_Diplocaulus;
    private List<IDiplocaulusActions> m_DiplocaulusActionsCallbackInterfaces = new List<IDiplocaulusActions>();
    private readonly InputAction m_Diplocaulus_Move;
    private readonly InputAction m_Diplocaulus_Collect;
    private readonly InputAction m_Diplocaulus_BabyFollow;
    private readonly InputAction m_Diplocaulus_BabyAction;
    private readonly InputAction m_Diplocaulus_CamMove;
    private readonly InputAction m_Diplocaulus_CamReset;
    public struct DiplocaulusActions
    {
        private @Controls m_Wrapper;
        public DiplocaulusActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Diplocaulus_Move;
        public InputAction @Collect => m_Wrapper.m_Diplocaulus_Collect;
        public InputAction @BabyFollow => m_Wrapper.m_Diplocaulus_BabyFollow;
        public InputAction @BabyAction => m_Wrapper.m_Diplocaulus_BabyAction;
        public InputAction @CamMove => m_Wrapper.m_Diplocaulus_CamMove;
        public InputAction @CamReset => m_Wrapper.m_Diplocaulus_CamReset;
        public InputActionMap Get() { return m_Wrapper.m_Diplocaulus; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DiplocaulusActions set) { return set.Get(); }
        public void AddCallbacks(IDiplocaulusActions instance)
        {
            if (instance == null || m_Wrapper.m_DiplocaulusActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DiplocaulusActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Collect.started += instance.OnCollect;
            @Collect.performed += instance.OnCollect;
            @Collect.canceled += instance.OnCollect;
            @BabyFollow.started += instance.OnBabyFollow;
            @BabyFollow.performed += instance.OnBabyFollow;
            @BabyFollow.canceled += instance.OnBabyFollow;
            @BabyAction.started += instance.OnBabyAction;
            @BabyAction.performed += instance.OnBabyAction;
            @BabyAction.canceled += instance.OnBabyAction;
            @CamMove.started += instance.OnCamMove;
            @CamMove.performed += instance.OnCamMove;
            @CamMove.canceled += instance.OnCamMove;
            @CamReset.started += instance.OnCamReset;
            @CamReset.performed += instance.OnCamReset;
            @CamReset.canceled += instance.OnCamReset;
        }

        private void UnregisterCallbacks(IDiplocaulusActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Collect.started -= instance.OnCollect;
            @Collect.performed -= instance.OnCollect;
            @Collect.canceled -= instance.OnCollect;
            @BabyFollow.started -= instance.OnBabyFollow;
            @BabyFollow.performed -= instance.OnBabyFollow;
            @BabyFollow.canceled -= instance.OnBabyFollow;
            @BabyAction.started -= instance.OnBabyAction;
            @BabyAction.performed -= instance.OnBabyAction;
            @BabyAction.canceled -= instance.OnBabyAction;
            @CamMove.started -= instance.OnCamMove;
            @CamMove.performed -= instance.OnCamMove;
            @CamMove.canceled -= instance.OnCamMove;
            @CamReset.started -= instance.OnCamReset;
            @CamReset.performed -= instance.OnCamReset;
            @CamReset.canceled -= instance.OnCamReset;
        }

        public void RemoveCallbacks(IDiplocaulusActions instance)
        {
            if (m_Wrapper.m_DiplocaulusActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDiplocaulusActions instance)
        {
            foreach (var item in m_Wrapper.m_DiplocaulusActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DiplocaulusActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DiplocaulusActions @Diplocaulus => new DiplocaulusActions(this);
    public interface IDiplocaulusActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnCollect(InputAction.CallbackContext context);
        void OnBabyFollow(InputAction.CallbackContext context);
        void OnBabyAction(InputAction.CallbackContext context);
        void OnCamMove(InputAction.CallbackContext context);
        void OnCamReset(InputAction.CallbackContext context);
    }
}
